---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: "/root/.ssh/{{ PROJECT_NAME }}"
  tasks:
    - name: Update the software package repository
      yum:
        name: "*"
        update_cache: yes
        
    - name: Install dependencies
      package:
        name:
          - java-1.8.0-openjdk
          - git
          - texlive-latex
          - wget
          - deltarpm
        state: present
        
    - name: Download jenkins repo
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: Import Jenkins CI key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Install Jenkins
      yum:
        name: "jenkins"
        state: present

    - name: Allow port 8080
      shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

    - name: Start the server
      service:
        name: jenkins
        state: started

    - name: Wait for Jenkins fully started
      wait_for:
        timeout: 120
        
    - name: Get initial admin Password
      become: yes
      become_method: sudo
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: password
      
    - name: Save initial admin password
      local_action: copy content={{ password.stdout }} dest=jenkinsInitPass.txt
